server:
  port: 8085

spring:
  application:
    name: report-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: shreyanshtelrandhe234@gmail.com
    password: fqco xtdp pmvy icnm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka